root = "."
tmp_dir = "build"

[build]
  bin = "./build/main"
  cmd = "go build -o ./build/main ."
  delay = 1000

  exclude_dir = ["assets", "tmp", "vendor", "build", "test", ".vscode", ".github", "README.md"]
  exclude_file = []
  exclude_regex = []

  exclude_unchanged = false
  follow_symlink = false

  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]

  kill_delay = "0s"
  log = "build-errors.log" # Logs build errors
  send_interrupt = false
  stop_on_error = true

  build_args = ""         # Arguments passed to the go build command
  run_args = ""           # Arguments passed to the binary when executed

  notify = true           # Enable notifications when build completes
  notify_command = ""     # Command to run when the build succeeds/fails

[color]
  app = ""                # No color for app output (you can set to "blue", etc.)
  build = "yellow"        # Yellow for build output
  main = "magenta"        # Magenta for main process output
  runner = "green"        # Green for runner process
  watcher = "cyan"        # Cyan for watcher process

[log]
  time = true             # Enable timestamps in logs for easier debugging

[misc]
  clean_on_exit = true    # Automatically clean up temp files on exit
  restart_on_file_change = true  # Restart the app when certain files change

[watch]
  debounce = 500          # Debounce watcher to reduce unnecessary rebuilds
  interval = "500ms"      # Set how frequently to check for file changes

[notifications]
  slack_webhook = ""      # Add a Slack webhook to send notifications on build success/failure
  email = ""              # Add email for sending build notifications
