root = "."
tmp_dir = "build"

[build]
  bin = "./build/main"
  cmd = "go build -o ./build/main ."
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "build", "test", ".vscode", ".github", "README.md"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log" # Logs build errors
  send_interrupt = false
  stop_on_error = true
  build_args = ""
  run_args = ""
  notify = true
  notify_command = ""

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true

[misc]
  clean_on_exit = true
  restart_on_file_change = true

[watch]
  debounce = 500
  interval = "500ms"

[notifications]
  slack_webhook = ""
  email = ""
