FROM golang:1.23-alpine AS dev

RUN apk add --no-cache git build-base curl

RUN curl -sSfL https://raw.githubusercontent.com/air-verse/air/master/install.sh | sh -s -- -b /usr/local/bin

ENV PATH="/usr/local/bin:$PATH"

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

CMD ["/usr/local/bin/air"]
