// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Article  string
	Author   string
	Products string
}{
	Article:  "article",
	Author:   "author",
	Products: "products",
}
